// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA612NCcibBg_MdKjTDlvyPwFfn4tVLmYo',
    appId: '1:766516250186:android:4fb9d2f79ca555fa2988b3',
    messagingSenderId: '766516250186',
    projectId: 'pokedex-122fb',
    databaseURL: 'https://pokedex-122fb-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-122fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRLUQE_sIzqIyn_qxIal1vO46nrwMbfQ',
    appId: '1:766516250186:ios:438ae52bc064e19e2988b3',
    messagingSenderId: '766516250186',
    projectId: 'pokedex-122fb',
    databaseURL: 'https://pokedex-122fb-default-rtdb.firebaseio.com',
    storageBucket: 'pokedex-122fb.appspot.com',
    androidClientId: '766516250186-rtnca3ah8ubi3d4t5hohb6doa97v8sno.apps.googleusercontent.com',
    iosClientId: '766516250186-n4de4p69m945gl7tegbgvkleme334phq.apps.googleusercontent.com',
    iosBundleId: 'com.pokedex.flutter.pokedex',
  );
}
